version: '3.8'

services:
  zeebufp:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: zeebufp
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./nginx/ssl:/etc/nginx/ssl:ro
    user: "www-data:www-data"
    environment:
      APP_ENV: production
    ports:
      - "8083:8083"
    expose:
      - "8083"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    external: true
