version: '3.8'

services:
  zeebufp:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: zeebufp
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment:
      APP_ENV: production
    ports:
      - "8083:8083"
    expose:
      - "8083"
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    external: true
